### ISSUE TITLE
How to compute with a new 'transfrom-origin' ?

### ISSUE THREAD

**Issue by gaopengpian** [jlmakes/rematrix#3]
I want to change `transform-origin`, then apply scale...
But Rematrix still uses the old `transform-origin`.

**Comment by jlmakes** [comment]
Please provide a minimal demonstration.

**Comment by gaopengpian** [comment]
I used a complex method to fixed it :
// center_dx and center_dy is the relative displacement between new origin and old origin

        translate_svg(center_dx, center_dy);
        scale_svg(scale_rate);
        translate_svg(-center_dx, -center_dy);

If rematrix can set the origin arguments ,  that will be better.
