### ISSUE TITLE
reshaping 3d matrix to 2d matrix

### ISSUE THREAD

**Issue by chadams** [jlmakes/rematrix#4]
Is it possible to reshape 3dmatrix[16] to a 2dmatrix[9]?

**Comment by jlmakes** [comment]
`Rematrix.format()` converts 2dmatrix[6] to 3dmatrix[16], but there is no built-in to do the reverse. 

Also, the 2D matrix in CSS is modeled with 6 values: `matrix(a, b, c, d, tx, ty)` (See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix)), but when displayed as a square matrix (the 9 values you mention) it would be:

```
a | c | tx
b | d | ty
0 | 0 | 1
```

So, if you wanted to do this conversion yourself, the corresponding values can be found in the 3dmatrix[16] like so:

```
matrix3d(a, b, 0, 0, c, d, 0, 0, 0, 0, 1, 0, tx, ty, 0, 1)
```
